# Generated by Django 2.1.7 on 2019-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Naziv vloge.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Vloge',
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Naziv žanra.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Žanri',
            },
        ),
    ]
