# Generated by Django 2.1.7 on 2019-02-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0002_vloga_zanr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(help_text='Naslov filma.', max_length=200)),
                ('dolzina', models.IntegerField(help_text='Dolžina filma v minutah.')),
                ('leto', models.PositiveSmallIntegerField(help_text='Leto premiere filma.')),
                ('ocena', models.FloatField(help_text='Ocena filma od 1 do 10.', null=True)),
                ('metascore', models.FloatField(help_text='Ocena filma od 1 do 10.', null=True)),
                ('zasluzek', models.IntegerField(help_text='Zaslužek v USD.', null=True)),
                ('opis', models.TextField(help_text='Opis filma.')),
            ],
            options={
                'verbose_name_plural': 'Filmi',
            },
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'verbose_name': 'Žanr', 'verbose_name_plural': 'Žanri'},
        ),
        migrations.AddField(
            model_name='film',
            name='zanr',
            field=models.ManyToManyField(help_text='Žanri tega filma', to='filmiapp.Zanr'),
        ),
    ]
