# Generated by Django 2.1.7 on 2019-03-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0003_auto_20190222_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nastopanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmiapp.Film')),
                ('oseba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmiapp.Oseba')),
                ('vloga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmiapp.Vloga')),
            ],
            options={
                'verbose_name_plural': 'Nastopanja',
            },
        ),
    ]
