# Generated by Django 2.1.7 on 2019-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0004_nastopanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='glasovi',
            field=models.IntegerField(help_text='Stevilo glasov za oceno.', null=True),
        ),
    ]
